- hosts: controller
  vars:
    host_group: "{{ groups['controller'] }}"
    host_group_size: "{{ host_group | length }}"
    exe_dest: "/tmp/{{ controller.bin_name }}"
    config_dest: "/tmp/{{ controller.config_name }}"
  vars_files:
    - group_vars/all.yml

  tasks:
  - name: limit count
    ansible.builtin.assert:
      that: host_group_size == "1"
      fail_msg: "Can only support one controller"
      success_msg: "Good on number of controllers, got {{ host_group_size }}"

  # - name: print paths
  #   debug:
  #     msg: "exe src: {{ilúvatar_home}}/target/release/{{controller.bin_name}}"

  - name: Get running controller process
    shell: "ps -ef | grep -v grep | grep -w {{ controller.bin_name }} | awk '{print $2}'"
    register: running_lb

  - name: Kill running controller process
    shell: "kill {{ item }}"
    with_items: "{{ running_lb.stdout_lines }}"
    become: yes

  - name: copy controller executable
    ansible.builtin.copy:
      src: "{{ilúvatar_home}}/target/release/{{controller.bin_name}}"
      dest: "{{exe_dest}}"
      mode: "preserve"

  - name: copy controller config
    ansible.builtin.copy:
      src: "{{ilúvatar_home}}/target/release/{{controller.config_name}}"
      dest: "{{config_dest}}"
      mode: "preserve"

  - name: run controller executable
    ansible.builtin.command: 
      argv: 
        - "{{exe_dest}}"
        - -c 
        - "{{config_dest}}"
    become: yes
    async: 2592000               # 60*60*24*30 – 1 month
    poll: 0
    when: mode != "clean"
    environment:
      "ILUVATAR_CONTROLLER__name": "{{ controller.host }}"
      "ILUVATAR_CONTROLLER__port": "{{ controller.port }}"
      "ILUVATAR_CONTROLLER__load_balancer__algorithm" : "{{ controller.algorithm }}"
      "ILUVATAR_CONTROLLER__graphite__address" : "{{ graphite.address }}"
      "ILUVATAR_CONTROLLER__graphite__api_port" : "{{ graphite.api_port }}"

  - name: wait until the controller on this host is up and running
    uri:
      url:
        "http://{{ansible_host}}:{{controller.port}}/ping"
      validate_certs: "no"
    register: result
    until: result.status == 200
    retries: 10
    delay: 5
    when: mode != "clean"
