- hosts: graphite
  vars:
    host_group: "{{ groups['graphite'] }}"
    host_group_size: "{{ host_group | length }}"
  vars_files:
    - group_vars/all.yml

  tasks:
  - name: limit count
    ansible.builtin.assert:
      that: host_group_size == "1"
      fail_msg: "Can only support one graphite node"
      success_msg: "Good on number of graphite nodes, got {{ host_group_size }}"

  - name: "pull the graphite image"
    shell: "docker pull {{ graphite.docker_image }}"
    register: result
    until: (result.rc == 0)
    retries: 2
    when: mode != "clean"

  - name: Remove container
    docker_container:
      name: "{{ graphite.container_name }}"
      state: absent

  - name: start controller
    docker_container:
      # https://graphite.readthedocs.io/en/latest/install.html?highlight=docker#docker
      name: "{{ graphite.container_name }}"
      image:
        "{{ graphite.docker_image }}"
      state: started
      restart_policy: "always"
      ports:
        - "{{ graphite.api_port }}:80"
        - "{{ graphite.ingestion_port }}:2003"

  - name: wait until graphite is up and running
    uri:
      url:
        "http://{{ansible_host}}:{{graphite.api_port}}"
      validate_certs: "no"
    register: result
    until: result.status == 200
    retries: 10
    delay: 10
    when: mode != "clean"
