- hosts: workers
  vars:
    expected: "Connection failure: [Errno 104] Connection reset by peer"
  vars_files:
    - group_vars/all.yml

  tasks:
  - name: Get running worker process
    shell: "ps -ef | grep -v grep | grep -w {{ worker.bin_name }} | awk '{print $2}'"
    register: running_worker

  # - name: find controller
  #   debug:
  #     msg: "{{ hostvars[ controller ].ansible_host }}"

  - name: Kill running worker process
    shell: "kill {{ item }}"
    with_items: "{{ running_worker.stdout_lines }}"
    become: yes

  - name: clean host
    ansible.builtin.command: 
      argv: 
        - "/home/alex/repos/efaas/src/Ilúvatar/target/debug/{{ worker.bin_name }}"
        - -c 
        - /home/alex/repos/efaas/src/Ilúvatar/worker/src/worker.json
        - clean
    become: yes

  - name: run worker executable
    ansible.builtin.command: 
      argv: 
        - "/home/alex/repos/efaas/src/Ilúvatar/target/debug/{{ worker.bin_name }}"
        - -c 
        - /home/alex/repos/efaas/src/Ilúvatar/worker/src/worker.json
    become: yes
    async: 2592000               # 60*60*24*30 – 1 month
    poll: 0
    when: mode != "clean"
    environment:
      "ILUVATAR_WORKER__name": "{{ inventory_hostname }}"
      "ILUVATAR_WORKER__port": "{{ worker.port }}"
      "ILUVATAR_WORKER__load_balancer_url" : "http://{{ controller.host }}:8089"
      "ILUVATAR_WORKER__graphite__address" : "{{ graphite.address }}"
      "ILUVATAR_WORKER__graphite__ingestion_port" : "{{ graphite.ingestion_port }}"
      "ILUVATAR_WORKER__graphite__ingestion_udp" : "{{ graphite.ingestion_udp }}"

  - name: print expected
    debug:
      msg: "expected: {{ expected }}"

  - name: wait until the worker on this host is up and running
    ansible.builtin.uri:
      url:
        "http://{{ansible_host}}:{{worker.port}}/ping"
      validate_certs: "no"
      # RPC server doesn't accept basic HTTP connections
      # but we can try connecting to it once it's up and know it's alive
      status_code: [-1, 0.9, 1.1]
    register: result
    until: result.msg == expected
    retries: 10
    delay: 10
    when: mode != "clean"
