[workspace]

# [package]
# name = "Ilúvatar"
# version = "0.1.0"
# edition = "2021"
# authors = ["Alex Fuerst alfuerst@iu.edu"]

members = [
  "worker",
  "worker_cli",
  "load_gen",
  "ilúvatar_lib",
  "load_balancer"
]

[profile.dev]
opt-level=0
debug=2
debug-assertions=true
overflow-checks=true
lto=false
incremental=true

[profile.release]
opt-level=3
lto=true
debug=0
debug-assertions=false
overflow-checks=false
incremental=false
strip=true
panic="abort"
