ilúvatar_home: "{{ lookup('env', 'ILU_HOME') | default(playbook_dir ~ '/..', true) }}"
mode: deploy
target: release

graphite:
  docker_image: graphiteapp/graphite-statsd:latest
  container_name: "iluvatar_graphite"
  api_port: 8000
  ingestion_port: 2003
  ingestion_udp: false
  address: localhost
  enabled: "{{ graphite_enabled | default(true) }}"

controller:
  bin_name: "ilúvatar_controller"
  config_name: "controller.json"
  host: "{{ hostvars[ groups['controller']|first ].ansible_host }}"
  port: "{{ controller_port | default(8089) }}"
  algorithm: "{{ controller_algorithm | default('RoundRobin') }}"

worker:
  bin_name: "ilúvatar_worker"
  config_name: "worker.json"
  port: "{{ worker_port | default(8070) }}"
